# Generated by Django 4.1.7 on 2023-02-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del libro')),
                ('autor', models.CharField(max_length=250, verbose_name='Nombre del autor')),
                ('isbn', models.IntegerField(default=0, verbose_name='ISBN')),
                ('edicion', models.IntegerField(default=1, verbose_name='Número de edición')),
                ('fecha_pub', models.DateField(verbose_name='Fecha de publicación')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'db_table': 'libros',
            },
        ),
    ]
